import { Component, VERSION } from '@angular/core';
import { Food } from './food.model';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular ' + VERSION.major;

  foods: Food[] = [];

  constructor(
  ) {}

  ngOnInit(): void {
    this.foods.push({
      id: 'test1',
      name: 'food1',
      brand: 'brand1',
      flavor: 'chicken',
      ingredients: [
        "Deboned Chicken", 
        "Chicken Meal", 
        "Ground Brown Rice", 
        "Barley", 
        "Peas", 
        "Oats", 
        "Chicken Fat (preserved with Mixed Tocopherols)", 
        "Salmon Meal", 
        "Tomato Pomace", 
        "Oatmeal", 
        "Tomatoes", 
        "Carrots", 
        "Natural Chicken Flavor", 
        "Ground Flaxseed", 
        "Choline Chloride", 
        "Spinach", 
        "Vitamin E Supplement", 
        "Taurine", 
        "Zinc Proteinate", 
        "Mixed Tocopherols added to preserve freshness", 
        "Sweet Potatoes", 
        "Apples", 
        "Blueberries", 
        "Zinc Sulfate", 
        "Calcium Carbonate", 
        "Niacin", 
        "Ferrous Sulfate", 
        "Iron Proteinate", 
        "Vitamin A Supplement", 
        "Glucosamine Hydrochloride", 
        "Chondroitin Sulfate", 
        "Ascorbic Acid (Vitamin C)", 
        "Copper Sulfate", 
        "Thiamine Mononitrate", 
        "Copper Proteinate", 
        "Chicory Root Extract", 
        "Manganese Proteinate", 
        "Manganese Sulfate", 
        "d-Calcium Pantothenate", 
        "Sodium Selenite", 
        "Pyridoxine Hydrochloride", 
        "Riboflavin", 
        "Yucca Schidigera Extract", 
        "Garlic Powder", 
        "Vitamin D3 Supplement", 
        "Biotin", 
        "Calcium Iodate", 
        "Vitamin B12 Supplement", 
        "Folic Acid", 
        "Dried Lactobacillus plantarum Fermentation Product", 
        "Dried Enterococcus faecium Fermentation Product", 
        "Dried Lactobacillus casei Fermentation Product", 
        "Dried Lactobacillus acidophilus Fermentation Product", 
        "Rosemary Extract", 
        "Green Tea Extract", 
        "Spearmint Extract"
      ],
      imagePath: ''
    })
    this.foods.push({
      id: 'test2',
      name: 'food2',
      brand: 'brand2',
      flavor: 'turkey',
      ingredients: [
        "Deboned Chicken", 
        "Chicken Meal", 
        "Ground Brown Rice", 
        "Barley", 
        "Peas", 
        "Oats", 
        "Chicken Fat (preserved with Mixed Tocopherols)", 
        "Salmon Meal", 
        "Tomato Pomace", 
        "Oatmeal", 
        "Tomatoes", 
        "Carrots", 
        "Natural Chicken Flavor", 
        "Ground Flaxseed", 
        "Choline Chloride", 
        "Spinach", 
        "Vitamin E Supplement", 
        "Taurine", 
        "Zinc Proteinate", 
        "Mixed Tocopherols added to preserve freshness", 
        "Sweet Potatoes", 
        "Apples", 
        "Blueberries", 
        "Zinc Sulfate", 
        "Calcium Carbonate", 
        "Niacin", 
        "Ferrous Sulfate", 
        "Iron Proteinate", 
        "Vitamin A Supplement", 
        "Glucosamine Hydrochloride", 
        "Chondroitin Sulfate", 
        "Ascorbic Acid (Vitamin C)", 
        "Copper Sulfate", 
        "Thiamine Mononitrate", 
        "Copper Proteinate", 
        "Chicory Root Extract", 
        "Manganese Proteinate", 
        "Manganese Sulfate", 
        "d-Calcium Pantothenate", 
        "Sodium Selenite", 
        "Pyridoxine Hydrochloride", 
        "Riboflavin", 
        "Yucca Schidigera Extract", 
        "Garlic Powder", 
        "Vitamin D3 Supplement", 
        "Biotin", 
        "Calcium Iodate", 
        "Vitamin B12 Supplement", 
        "Folic Acid", 
        "Dried Lactobacillus plantarum Fermentation Product", 
        "Dried Enterococcus faecium Fermentation Product", 
        "Dried Lactobacillus casei Fermentation Product", 
        "Dried Lactobacillus acidophilus Fermentation Product", 
        "Rosemary Extract", 
        "Green Tea Extract", 
        "Spearmint Extract"
      ],
      imagePath: ''
    })
    this.foods.push({
      id: 'test2',
      name: 'food2',
      brand: 'brand2',
      flavor: 'turkey',
      ingredients: [
        "Deboned Chicken", 
        "Chicken Meal", 
        "Ground Brown Rice", 
        "Barley", 
        "Peas", 
        "Oats", 
        "Chicken Fat (preserved with Mixed Tocopherols)", 
        "Salmon Meal", 
        "Tomato Pomace", 
        "Oatmeal", 
        "Tomatoes", 
        "Carrots", 
        "Natural Chicken Flavor", 
        "Ground Flaxseed", 
        "Choline Chloride", 
        "Spinach", 
        "Vitamin E Supplement", 
        "Taurine", 
        "Zinc Proteinate", 
        "Mixed Tocopherols added to preserve freshness", 
        "Sweet Potatoes", 
        "Apples", 
        "Blueberries", 
        "Zinc Sulfate", 
        "Calcium Carbonate", 
        "Niacin", 
        "Ferrous Sulfate", 
        "Iron Proteinate", 
        "Vitamin A Supplement", 
        "Glucosamine Hydrochloride", 
        "Chondroitin Sulfate", 
        "Ascorbic Acid (Vitamin C)", 
        "Copper Sulfate", 
        "Thiamine Mononitrate", 
        "Copper Proteinate", 
        "Chicory Root Extract", 
        "Manganese Proteinate", 
        "Manganese Sulfate", 
        "d-Calcium Pantothenate", 
        "Sodium Selenite", 
        "Pyridoxine Hydrochloride", 
        "Riboflavin", 
        "Yucca Schidigera Extract", 
        "Garlic Powder", 
        "Vitamin D3 Supplement", 
        "Biotin", 
        "Calcium Iodate", 
        "Vitamin B12 Supplement", 
        "Folic Acid", 
        "Dried Lactobacillus plantarum Fermentation Product", 
        "Dried Enterococcus faecium Fermentation Product", 
        "Dried Lactobacillus casei Fermentation Product", 
        "Dried Lactobacillus acidophilus Fermentation Product", 
        "Rosemary Extract", 
        "Green Tea Extract", 
        "Spearmint Extract"
      ],
      imagePath: ''
    })
    this.foods.push({
      id: 'test2',
      name: 'food2',
      brand: 'brand2',
      flavor: 'turkey',
      ingredients: [
        "Deboned Chicken", 
        "Chicken Meal", 
        "Ground Brown Rice", 
        "Barley", 
        "Peas", 
        "Oats", 
        "Chicken Fat (preserved with Mixed Tocopherols)", 
        "Salmon Meal", 
        "Tomato Pomace", 
        "Oatmeal", 
        "Tomatoes", 
        "Carrots", 
        "Natural Chicken Flavor", 
        "Ground Flaxseed", 
        "Choline Chloride", 
        "Spinach", 
        "Vitamin E Supplement", 
        "Taurine", 
        "Zinc Proteinate", 
        "Mixed Tocopherols added to preserve freshness", 
        "Sweet Potatoes", 
        "Apples", 
        "Blueberries", 
        "Zinc Sulfate", 
        "Calcium Carbonate", 
        "Niacin", 
        "Ferrous Sulfate", 
        "Iron Proteinate", 
        "Vitamin A Supplement", 
        "Glucosamine Hydrochloride", 
        "Chondroitin Sulfate", 
        "Ascorbic Acid (Vitamin C)", 
        "Copper Sulfate", 
        "Thiamine Mononitrate", 
        "Copper Proteinate", 
        "Chicory Root Extract", 
        "Manganese Proteinate", 
        "Manganese Sulfate", 
        "d-Calcium Pantothenate", 
        "Sodium Selenite", 
        "Pyridoxine Hydrochloride", 
        "Riboflavin", 
        "Yucca Schidigera Extract", 
        "Garlic Powder", 
        "Vitamin D3 Supplement", 
        "Biotin", 
        "Calcium Iodate", 
        "Vitamin B12 Supplement", 
        "Folic Acid", 
        "Dried Lactobacillus plantarum Fermentation Product", 
        "Dried Enterococcus faecium Fermentation Product", 
        "Dried Lactobacillus casei Fermentation Product", 
        "Dried Lactobacillus acidophilus Fermentation Product", 
        "Rosemary Extract", 
        "Green Tea Extract", 
        "Spearmint Extract"
      ],
      imagePath: ''
    })
    this.foods.push({
      id: 'test2',
      name: 'food2',
      brand: 'brand2',
      flavor: 'turkey',
      ingredients: [
        "Deboned Chicken", 
        "Chicken Meal", 
        "Ground Brown Rice", 
        "Barley", 
        "Peas", 
        "Oats", 
        "Chicken Fat (preserved with Mixed Tocopherols)", 
        "Salmon Meal", 
        "Tomato Pomace", 
        "Oatmeal", 
        "Tomatoes", 
        "Carrots", 
        "Natural Chicken Flavor", 
        "Ground Flaxseed", 
        "Choline Chloride", 
        "Spinach", 
        "Vitamin E Supplement", 
        "Taurine", 
        "Zinc Proteinate", 
        "Mixed Tocopherols added to preserve freshness", 
        "Sweet Potatoes", 
        "Apples", 
        "Blueberries", 
        "Zinc Sulfate", 
        "Calcium Carbonate", 
        "Niacin", 
        "Ferrous Sulfate", 
        "Iron Proteinate", 
        "Vitamin A Supplement", 
        "Glucosamine Hydrochloride", 
        "Chondroitin Sulfate", 
        "Ascorbic Acid (Vitamin C)", 
        "Copper Sulfate", 
        "Thiamine Mononitrate", 
        "Copper Proteinate", 
        "Chicory Root Extract", 
        "Manganese Proteinate", 
        "Manganese Sulfate", 
        "d-Calcium Pantothenate", 
        "Sodium Selenite", 
        "Pyridoxine Hydrochloride", 
        "Riboflavin", 
        "Yucca Schidigera Extract", 
        "Garlic Powder", 
        "Vitamin D3 Supplement", 
        "Biotin", 
        "Calcium Iodate", 
        "Vitamin B12 Supplement", 
        "Folic Acid", 
        "Dried Lactobacillus plantarum Fermentation Product", 
        "Dried Enterococcus faecium Fermentation Product", 
        "Dried Lactobacillus casei Fermentation Product", 
        "Dried Lactobacillus acidophilus Fermentation Product", 
        "Rosemary Extract", 
        "Green Tea Extract", 
        "Spearmint Extract"
      ],
      imagePath: ''
    })
    this.foods.push({
      id: 'test2',
      name: 'food2',
      brand: 'brand2',
      flavor: 'turkey',
      ingredients: [
        "Deboned Chicken", 
        "Chicken Meal", 
        "Ground Brown Rice", 
        "Barley", 
        "Peas", 
        "Oats", 
        "Chicken Fat (preserved with Mixed Tocopherols)", 
        "Salmon Meal", 
        "Tomato Pomace", 
        "Oatmeal", 
        "Tomatoes", 
        "Carrots", 
        "Natural Chicken Flavor", 
        "Ground Flaxseed", 
        "Choline Chloride", 
        "Spinach", 
        "Vitamin E Supplement", 
        "Taurine", 
        "Zinc Proteinate", 
        "Mixed Tocopherols added to preserve freshness", 
        "Sweet Potatoes", 
        "Apples", 
        "Blueberries", 
        "Zinc Sulfate", 
        "Calcium Carbonate", 
        "Niacin", 
        "Ferrous Sulfate", 
        "Iron Proteinate", 
        "Vitamin A Supplement", 
        "Glucosamine Hydrochloride", 
        "Chondroitin Sulfate", 
        "Ascorbic Acid (Vitamin C)", 
        "Copper Sulfate", 
        "Thiamine Mononitrate", 
        "Copper Proteinate", 
        "Chicory Root Extract", 
        "Manganese Proteinate", 
        "Manganese Sulfate", 
        "d-Calcium Pantothenate", 
        "Sodium Selenite", 
        "Pyridoxine Hydrochloride", 
        "Riboflavin", 
        "Yucca Schidigera Extract", 
        "Garlic Powder", 
        "Vitamin D3 Supplement", 
        "Biotin", 
        "Calcium Iodate", 
        "Vitamin B12 Supplement", 
        "Folic Acid", 
        "Dried Lactobacillus plantarum Fermentation Product", 
        "Dried Enterococcus faecium Fermentation Product", 
        "Dried Lactobacillus casei Fermentation Product", 
        "Dried Lactobacillus acidophilus Fermentation Product", 
        "Rosemary Extract", 
        "Green Tea Extract", 
        "Spearmint Extract"
      ],
      imagePath: ''
    })
    this.foods.push({
      id: 'test2',
      name: 'food2',
      brand: 'brand2',
      flavor: 'turkey',
      ingredients: [
        "Deboned Chicken", 
        "Chicken Meal", 
        "Ground Brown Rice", 
        "Barley", 
        "Peas", 
        "Oats", 
        "Chicken Fat (preserved with Mixed Tocopherols)", 
        "Salmon Meal", 
        "Tomato Pomace", 
        "Oatmeal", 
        "Tomatoes", 
        "Carrots", 
        "Natural Chicken Flavor", 
        "Ground Flaxseed", 
        "Choline Chloride", 
        "Spinach", 
        "Vitamin E Supplement", 
        "Taurine", 
        "Zinc Proteinate", 
        "Mixed Tocopherols added to preserve freshness", 
        "Sweet Potatoes", 
        "Apples", 
        "Blueberries", 
        "Zinc Sulfate", 
        "Calcium Carbonate", 
        "Niacin", 
        "Ferrous Sulfate", 
        "Iron Proteinate", 
        "Vitamin A Supplement", 
        "Glucosamine Hydrochloride", 
        "Chondroitin Sulfate", 
        "Ascorbic Acid (Vitamin C)", 
        "Copper Sulfate", 
        "Thiamine Mononitrate", 
        "Copper Proteinate", 
        "Chicory Root Extract", 
        "Manganese Proteinate", 
        "Manganese Sulfate", 
        "d-Calcium Pantothenate", 
        "Sodium Selenite", 
        "Pyridoxine Hydrochloride", 
        "Riboflavin", 
        "Yucca Schidigera Extract", 
        "Garlic Powder", 
        "Vitamin D3 Supplement", 
        "Biotin", 
        "Calcium Iodate", 
        "Vitamin B12 Supplement", 
        "Folic Acid", 
        "Dried Lactobacillus plantarum Fermentation Product", 
        "Dried Enterococcus faecium Fermentation Product", 
        "Dried Lactobacillus casei Fermentation Product", 
        "Dried Lactobacillus acidophilus Fermentation Product", 
        "Rosemary Extract", 
        "Green Tea Extract", 
        "Spearmint Extract"
      ],
      imagePath: ''
    })
  }
}
